version: '3.7'

services:
  collab_backend_web:
    container_name: collab_backend_web
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/app/docker/production-entrypoint.sh"]
    command: bash -c "
        python manage.py collectstatic --noinput &&
        python manage.py migrate &&
        gunicorn collab.wsgi:application --bind 0.0.0.0:8000 --log-file -"
    ports:
      - 80:8000
    env_file:
      - ./.env.production

  collab_backend_worker:
    container_name: collab_backend_worker
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/app/docker/production-entrypoint.sh"]
    command: celery -A collab worker -l info
    env_file:
      - ./.env.production

