# Generated by Django 3.0.4 on 2020-08-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0002_thread_is_resolves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='is_resolves',
            new_name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.AddField(
            model_name='organization',
            name='key',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
    ]
