# Generated by Django 3.0.4 on 2020-08-27 16:18

import collab_app.mixins.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0004_auto_20200825_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Accepted'), (3, 'Denied'), (4, 'Canceled'), (5, 'Accepted Deleted')], default=1)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collab_app_invite_related', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_sent', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='collab_app.Organization')),
            ],
            options={
                'abstract': False,
            },
            bases=(collab_app.mixins.models.ModelDiffMixin, models.Model),
        ),
    ]
