# Generated by Django 3.0.4 on 2020-08-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0006_auto_20200827_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Accepted'), (3, 'Denied'), (4, 'Canceled')], default=1),
        ),
        migrations.AddConstraint(
            model_name='invite',
            constraint=models.UniqueConstraint(fields=('organization', 'email', 'state'), name='unique_invite'),
        ),
    ]
