# Generated by Django 3.0.4 on 2020-09-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0008_auto_20200904_2201'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='collab_app_task_comment_or_design_edits',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='comment',
            new_name='description',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, description=''), models.Q(_negated=True, design_edits=''), _connector='OR'), name='collab_app_task_description_or_design_edits'),
        ),
    ]
