# Generated by Django 3.0.4 on 2020-09-05 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0009_auto_20200904_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmetadata',
            old_name='task_logged_at',
            new_name='url_origin',
        ),
    ]
