# Generated by Django 3.0.4 on 2020-09-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0010_auto_20200905_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='screenshot_url',
            new_name='element_screenshot_url',
        ),
        migrations.AddField(
            model_name='task',
            name='window_screenshot_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
