# Generated by Django 3.0.4 on 2020-09-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0011_auto_20200906_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='element_screenshot_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='window_screenshot_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
