# Generated by Django 3.0.4 on 2020-09-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0012_auto_20200906_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
