# Generated by Django 3.0.4 on 2020-09-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0013_auto_20200907_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='key',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
    ]
