# Generated by Django 3.0.4 on 2020-09-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0014_auto_20200907_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Dashboard'), (3, 'Widget')], default=2),
        ),
    ]
