# Generated by Django 3.0.4 on 2020-09-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0015_auto_20200907_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcolumn',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='task_columns', to='collab_app.Project'),
            preserve_default=False,
        ),
    ]
