# Generated by Django 3.0.4 on 2020-09-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0016_taskcolumn_project'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='collab_app_task_description_or_design_edits',
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, title=''), models.Q(_negated=True, design_edits=''), _connector='OR'), name='collab_app_task_title_or_design_edits'),
        ),
    ]
