# Generated by Django 3.0.4 on 2020-09-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0017_auto_20200908_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmetadata',
            old_name='browser',
            new_name='browser_name',
        ),
        migrations.RenameField(
            model_name='taskmetadata',
            old_name='browser_window',
            new_name='browser_version',
        ),
        migrations.RenameField(
            model_name='taskmetadata',
            old_name='operating_system',
            new_name='os_name',
        ),
        migrations.RenameField(
            model_name='taskmetadata',
            old_name='resolution',
            new_name='os_version',
        ),
        migrations.AddField(
            model_name='taskmetadata',
            name='browser_window_height',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskmetadata',
            name='browser_window_width',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskmetadata',
            name='device_pixel_ratio',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskmetadata',
            name='os_version_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='taskmetadata',
            name='pixel_depth',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskmetadata',
            name='screen_height',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskmetadata',
            name='screen_width',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taskmetadata',
            name='color_depth',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
