# Generated by Django 3.0.4 on 2020-09-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0018_auto_20200913_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
