# Generated by Django 3.0.4 on 2020-10-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0021_taskhtml'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcolumn',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
