# Generated by Django 3.0.4 on 2020-10-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0024_auto_20201029_2114'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='collab_app_task_title_or_design_edits',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, title=''), models.Q(_negated=True, design_edits=''), ('has_text_copy_changes', True), _connector='OR'), name='collab_app_task_title_or_design_edits_or_text_changes'),
        ),
    ]
