# Generated by Django 3.0.4 on 2020-11-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0025_auto_20201029_2336'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='collab_app_task_target_id_or_dom_path',
        ),
        migrations.AddField(
            model_name='task',
            name='has_target',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, target_id=''), models.Q(_negated=True, target_dom_path=''), ('has_target', False), _connector='OR'), name='collab_app_task_target_id_or_dom_path_or_no_target'),
        ),
    ]
