# Generated by Django 3.0.4 on 2020-11-20 17:12

import collab_app.mixins.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collab_app', '0026_auto_20201110_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDataUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('window_screenshot_data_url', models.TextField(default='')),
                ('element_screenshot_data_url', models.TextField(default='')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collab_app_taskdataurl_related', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_data_urls', to='collab_app.Task')),
            ],
            options={
                'abstract': False,
            },
            bases=(collab_app.mixins.models.ModelDiffMixin, models.Model),
        ),
    ]
